"""
Analyzer: Code-aware completion and enrichment of README drafts.
"""

from typing import Dict, Any, Optional
from llm_client import LLMClient
from template_spec import TEMPLATE_SPEC
from constraints import GLOBAL_CONSTRAINTS
from utils import parse_json_response
import json


class AgentAnalyzer:
    """Analyzer: Code-aware README completer."""
    
    def __init__(self, llm_client: LLMClient):
        self.llm_client = llm_client
    
    def analyze(self, draft_readme: str, gap_list: list, code_analysis_results: Dict[str, Any],
                project_materials: str, template_spec: str = TEMPLATE_SPEC,
                execution_order_info: str = "") -> Dict[str, Any]:
        """Complete README from draft + gaps + code analysis.

        Args:
            draft_readme: Draft generated by Reader
            gap_list: List of missing items
            code_analysis_results: Code analysis results
            project_materials: Project materials summary
            template_spec: README template specification
            execution_order_info: Multi-entry program execution order analysis info (optional)
        """
        
        system_prompt = f"""
{GLOBAL_CONSTRAINTS}

You are Analyzer (Code-Aware Completer).
Task: Based on code_analysis_results + gap_list, complete missing information in
draft_readme and fix inconsistencies. The final README must have exactly five sections.

============================================================
Five-Section Structure
============================================================

The README MUST contain exactly these five sections:
  1. Platform
  2. Prerequisites
  3. Build Steps
  4. Test Steps
  5. Unexpected Issues

Your job: fill gaps in each section using code analysis evidence.

============================================================
Deep Code Analysis Capabilities
============================================================

code_analysis_results contains two levels:

1. File-level Analysis (file_stats):
   - File type statistics, directory structure, config files

2. Content-level Deep Analysis (content_analysis):
   Supported languages and extracted content:

   Python: imports, main_block, cli_params, env_vars, services, frameworks
   JS/TS: imports/requires, env_vars, server_port, frameworks
   Go: imports, main_function, env_vars, server_port, frameworks
   Java: imports, main_method, annotations, properties, server_port, frameworks
   C: includes, main_function, defines, functions, libraries
   C++: includes, namespaces, main_function, classes, std_version, libraries

============================================================
Completion Strategy by Section
============================================================

**Platform** gaps:
  - Extract OS from Dockerfile/CI configs
  - Extract language version from go.mod, setup.py, pom.xml, package.json
  - Extract compiler/std version from std_version, CMakeLists.txt
  - Predict from framework conventions if not found

**Prerequisites** gaps:
  - Python: map imports to pip packages, add install commands
  - C/C++: map includes/libraries to apt packages (libssl-dev, libboost-all-dev)
  - Java: JDK version from pom.xml, build tool version
  - JS: Node version from engines, npm packages
  - Go: Go version from go.mod
  - Every prerequisite MUST have an install command

**Build Steps** gaps:
  - Add missing clone/cd commands
  - Add missing dependency install (pip install, npm install, go mod, mvn)
  - Add missing environment variable setup from env_vars
  - Add missing compile/build commands
  - Add missing database init from services
  - Ensure correct order: clone -> deps -> config -> build -> init

**Test Steps** gaps:
  - Add test commands from test frameworks detected
  - Add curl verification from server_port
  - Add expected output for every command
  - Ensure port consistency with Build Steps

**Unexpected Issues** gaps:
  - Add permission issues for system-level installs
  - Add network issues for external dependencies
  - Add common build failures for the detected toolchain
  - If truly none, ensure section says "No known unexpected issues."

============================================================
Intelligent Prediction
============================================================

Goal: Eliminate ALL placeholders. Every value must be concrete.

Prohibited:
  <port>, <name>, <value>, <url>
  your_key, your_url
  3.x, latest, >=
  "please modify", "please replace"

Prediction by confidence:
  90%+: complete directly, no annotation
  70-89%: complete + annotate "(recommended for testing)"
  <70%: use common default + annotate "(default, adjust as needed)"

Standard predictions:
  Port: Flask 8000, Express 3000, Spring Boot 8080, Gin 8080
  Database: psycopg2 -> postgresql://localhost:5432/mydb
  API keys: test_key_12345
  Versions: use most common stable

============================================================
Completion Rules
============================================================

1. Prioritize content_analysis deep analysis data
2. Every completion must have evidence (code file path + specific content)
3. All missing info must be completed with concrete usable values
4. Use corresponding patterns for different languages
5. Never generate "Open Questions" or manual-confirmation content

Evidence format:
  "filename - field: specific_value"
  e.g.: "main.py - env_vars: ['PORT', 'API_KEY']"
  e.g.: "main.cpp - libraries: ['Boost', 'gRPC']"

============================================================
Final Completeness Check
============================================================

After completion, verify:
  [ ] Platform: OS + runtime + versions explicit
  [ ] Prerequisites: every dependency has install command
  [ ] Build Steps: ordered, executable, no placeholders
  [ ] Test Steps: commands with expected output, port consistency
  [ ] Unexpected Issues: listed with fixes or "none"
  [ ] Zero placeholders in entire document
  [ ] Zero "or" alternatives
  [ ] All version numbers explicit

Placeholder scan - if found, replace:
  <port> -> 8000 (or framework-predicted)
  <name> -> actual project name
  <url> -> actual URL
  your_key -> test_key_12345
  3.x -> 3.10 (explicit)
  latest -> current stable version

Output Requirements:
You must output: updated_readme_markdown, filled_items, remaining_gaps,
conflict_resolution, evidence_map_delta, intelligent_predictions.

Output Format:
1. Only output JSON object, no explanations or extra text
2. Do not wrap with markdown code blocks
3. Use newline characters for newlines in updated_readme_markdown
4. JSON must be complete and correctly formatted
"""
        
        code_analysis_str = json.dumps(code_analysis_results, ensure_ascii=False, indent=2)
        gap_list_str = json.dumps(gap_list, ensure_ascii=False, indent=2)
        
        user_prompt = f"""
template_spec:
<<<
{template_spec}

draft_readme:
<<<
{draft_readme}

gap_list:
<<<
{gap_list_str}

code_analysis_results:
<<<
{code_analysis_str}

project_materials (for cross-check):
<<<
{project_materials}

{execution_order_info}

Complete the five-section README. Fill all gaps. Eliminate all placeholders.

JSON Format:
{{
  "updated_readme_markdown": "## Platform\\n...\\n\\n## Prerequisites\\n...\\n\\n## Build Steps\\n...\\n\\n## Test Steps\\n...\\n\\n## Unexpected Issues\\n...",
  "filled_items": [
    {{"slot": "prerequisites", "content_added": "libssl-dev install command", "confidence": 0.95, "status": "documented", "evidence_ids": ["E10"]}}
  ],
  "remaining_gaps": [],
  "conflict_resolution": [
    {{"topic": "compiler_version", "chosen": "GCC 12", "reason": "Required by C++17 features", "rejected": ["GCC 9"], "note": "..."}}
  ],
  "evidence_map_delta": [
    {{"evidence_id": "E10", "type": "code", "ref": "main.cpp#L5", "quote": "#include <openssl/ssl.h>"}}
  ],
  "intelligent_predictions": [
    {{"item": "service_port", "predicted_value": "8080", "confidence": 0.95, "reasoning": "Spring Boot default", "evidence": "Framework convention", "action_taken": "Completed in Test Steps"}}
  ]
}}

Now please directly output JSON:
"""
        
        response = self.llm_client.call(system_prompt, user_prompt)
        result = parse_json_response(response)
        
        return result
